version: '3.4'

services:
    app:
        build:
            context: .
        expose:
            - ${SERVER_PORT:-8080}
        ports:
            - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
        volumes:
            - ./:/usr/src/app
        environment:
            - SERVER_PORT=${SERVER_PORT:-8080}
